CREATE DATABASE PETSHOP;

USE PETSHOP;

CREATE TABLE CLIENTE  (
	CPF VARCHAR(11) NOT NULL,
	NOMECLI VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR (20),
    ENDERECO VARCHAR (100),
    DATANASC DATETIME NOT NULL,
    SEXO CHAR(1) NOT NULL);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF);

CREATE TABLE ANIMAL  (
	IDANIMAL INTEGER NOT NULL,
    CPFCLIENTE VARCHAR(11) NOT NULL, 
	NOMEANIMAL VARCHAR(20) NOT NULL,
    RACA VARCHAR (20),
    PORTE VARCHAR (30),
    ESPECIA VARCHAR (20),
    SEXO CHAR(1) NOT NULL);
ALTER TABLE ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY (IDANIMAL);
ALTER TABLE ANIMAL ADD CONSTRAINT FK_ANIMAL_CLIENTE FOREIGN KEY (CPFCLIENTE) REFERENCES CLIENTE (CPF); 

CREATE TABLE PRODUTO  (
	IDPRODUTO INTEGER NOT NULL,
	NOMEPRDOUTO VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR (100),
    VALOR NUMERIC(15,2));
ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (IDPRODUTO);

CREATE TABLE PRODUTO_CLIENTE (
	IDPRODUTO INTEGER NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    DATACOMPRA DATETIME NOT NULL,
    QTDS INTEGER NOT NULL);    
ALTER TABLE PRODUTO_CLIENTE ADD CONSTRAINT PK_PRODUTO_CLIENTE PRIMARY KEY (IDPRODUTO, CPF, DATACOMPRA);
ALTER TABLE PRODUTO_CLIENTE ADD CONSTRAINT FK_PRODUTOCLIENTE_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO); 
ALTER TABLE PRODUTO_CLIENTE ADD CONSTRAINT FK_PRODUTOCLIENTE_CLIENTE FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF); 
