USE PETSHOP;
DELIMITER $$

CREATE PROCEDURE SP_DELETARPRODUTO_CLIENTE (IDPRODUTO INTEGER, CPFCLIENTE VARCHAR(11), DATACOMPRA DATETIME)
BEGIN
	DELETE FROM PRODUTO_CLIENTE WHERE PRODUTO_CLIENTE.IDPRODUTO = IDPRODUTO
								AND PRODUTO_CLIENTE.CPF = CPFCLIENTE
								AND PRODUTO_CLIENTE.DATACOMPRA = DATACOMPRA;
END$$
DELIMITER ;