USE PETSHOP;
DELIMITER $$

CREATE PROCEDURE SP_INCLUIRANIMAL (IDANIMAL INTEGER ,
    CPFCLIENTE VARCHAR(11) , 
	NOMEANIMAL VARCHAR(20) ,
    RACA VARCHAR (20),
    PORTE VARCHAR (30),
    ESPECIE VARCHAR (20),
    SEXO CHAR(1))
BEGIN
	INSERT INTO ANIMAL (IDANIMAL, CPFCLIENTE, NOMEANIMAL, RACA, PORTE, ESPECIE,SEXO) 
		  VALUES (IDANIMAL, CPFCLIENTE, NOMEANIMAL, RACA, PORTE, ESPECIE,SEXO);
END$$
DELIMITER ;