USE PETSHOP;
DELIMITER $$

CREATE PROCEDURE SP_INCLUIRPRODUTO (IDPRODUTO INTEGER,
	NOMEPRODUTO VARCHAR(20),
    DESCRICAO VARCHAR (100),
    VALOR NUMERIC(15,2))
BEGIN
	INSERT INTO PRODUTO (IDPRODUTO, NOMEPRODUTO, DESCRICAO, VALOR) 
		  VALUES (IDPRODUTO, NOMEPRODUTO, DESCRICAO, VALOR);
END$$
DELIMITER ;